### ISSUE TITLE
Need to remove the annoying unsupported update error for unsupported iPhones like 4S.

### ISSUE THREAD

**Issue by antdude** [imoreapps/fh#1]
iPhone 4S' iOS v9.3.5's App Store keeps telling me File Hub Pro v7 is incompatible with iPhone 4S.

**Comment by antdude** [comment]
https://i.imgur.com/VS4x0yj.png for a screen shot/capture I took and shared.

**Comment by imoreapps** [comment]
Thanks for your feedback, we will look into it and get back to you.

Ant <notifications@github.com>于2019年1月30日 周三00:13写道：

**Comment by antdude** [comment]
Thanks. :)

**Comment by imoreapps** [comment]
We will bring it back to 32 bit iOS devices on next update.

**Comment by antdude** [comment]
OK and thanks! Do you have an ETA on when that will be?
